// Instrument-specific data. Shared scale rules live in js/scales.js.
InstrumentBuilder.build({
  id: "Baritone_BC",
  clef: "bass",
  transpose: {"semitones":0,"steps":0},
  notes: {
    "E2": {"fingering":["1","2","3"]},
    "F2": {"fingering":["1","3"]},
    "G2": {"fingering":["1","2"]},
    "A2": {"fingering":["2"]},
    "B2": {"fingering":["1","2","3"]},
    "C3": {"fingering":["1","3"]},
    "D3": {"fingering":["1","2"]},
    "E3": {"fingering":["2"]},
    "F3": {"fingering":[]},
    "G3": {"fingering":["1","2"]},
    "A3": {"fingering":["2"]},
    "B3": {"fingering":["1","2"]},
    "C4": {"fingering":["1"]},
    "D4": {"fingering":[]},
    "E4": {"fingering":["2"]},
    "F4": {"fingering":[]},
    "G4": {"fingering":["1","2"]},
    "A4": {"fingering":["2"]},
    "F#2": {"fingering":["2","3"]},
    "G#2": {"fingering":["1"]},
    "A#2": {"fingering":["1","2","3"]},
    "Bb2": {"fingering":[]},
    "Db3": {"fingering":["2","3"]},
    "D#3": {"fingering":["1"]},
    "F#3": {"fingering":["2","3"]},
    "G#3": {"fingering":["1"]},
    "A#3": {"fingering":[]},
    "Db4": {"fingering":["2"]},
    "D#4": {"fingering":["1"]},
    "F#4": {"fingering":["2","3"]},
    "G#4": {"fingering":["1"]},
    "A#4": {"fingering":[]},
  },
  levels: {
    "Level 1": ["Bb2","C3","D3","Eb3","F3"],
    "Level 2": ["G2","A2","Bb2","C3","D3","Eb3","F3","G3"],
    "Level 3": ["G2","Ab2","A2","Bb2","C3","D3","Eb3","F3","G3","Ab3","Bb3"],
    "Level 4": ["G2","Ab2","A2","Bb2","C3","Db3","D3","Eb3","E3","F3","G3","Ab3","A3","Bb3"],
  },
  scaleRoots: {
    "C": "C3",
    "F": "F3",
    "Bb": "Bb2",
    "Eb": "Eb3",
    "Ab": "Ab2",
    "Db": "Db3",
    "Gb": "Gb3",
    "Cb": "Cb3",
    "G": "G3",
    "D": "D3",
    "A": "A2",
    "E": "E3",
    "B": "B2",
    "F#": "F#3",
    "C#": "C#3",
  },
  minorRoots: {
    "A": "A2",
    "D": "D3",
    "G": "G3",
    "C": "C3",
    "F": "F3",
    "Bb": "Bb2",
    "Eb": "Eb3",
    "Ab": "Ab2",
    "E": "E3",
    "B": "B2",
    "F#": "F#3",
    "C#": "C#3",
    "G#": "G#3",
    "D#": "D#3",
    "A#": "A#2",
  },
  chromaticRoot: "Bb2",
});
