// Instrument-specific data. Shared scale rules live in js/scales.js.
InstrumentBuilder.build({
  id: "Clarinet",
  clef: "treble",
  transpose: {"semitones":2,"steps":1},
  notes: {
    "E3": {"fingering":["T","I","II","III","IV","V","VI","1","3"], "alternates": [["T","I","II","III","IV","V","VI","1"], ["T","I","II","III","IV","V","VI","A"]]},
    "F3": {"fingering":["T","I","II","III","IV","V","VI","3"], "alternates": [["T","I","II","III","IV","V","VI","C"]]},
    "G3": {"fingering":["T","I","II","III","IV","V","VI"]},
    "A3": {"fingering":["T","I","II","III","IV","V"]},
    "B3": {"fingering":["T","I","II","III","V"], "alternates": [["T","I","II","III","IV","5"]]},
    "C4": {"fingering":["T","I","II","III"]},
    "D4": {"fingering":["T","I","II"]},
    "E4": {"fingering":["T","I"]},
    "F4": {"fingering":["T"]},
    "G4": {"fingering":[], "alternates": [["IV","V","VI"]]},
    "A4": {"fingering":["10"], "alternates": [["10","IV","V","VI"]]},
    "B4": {"fingering":["12","T","I","II","III","IV","V","VI","1","3"], "alternates": [["12","T","I","II","III","IV","V","VI","1"], ["12","T","I","II","III","IV","V","VI","A"]]},
    "C5": {"fingering":["12","T","I","II","III","IV","V","VI","3"], "alternates": [["12","T","I","II","III","IV","V","VI","C"]]},
    "D5": {"fingering":["12","T","I","II","III","IV","V","VI"]},
    "E5": {"fingering":["12","T","I","II","III","IV","V"]},
    "F5": {"fingering":["12","T","I","II","III","IV"]},
    "G5": {"fingering":["12","T","I","II","III"]},
    "A5": {"fingering":["12","T","I","II"]},
    "B5": {"fingering":["12","T","I"]},
    "C6": {"fingering":["12","T"]},
    "D6": {"fingering":["12","T","II","III","IV"]},
    "E6": {"fingering":["12","T","II","III","4"]},
    "F6": {"fingering":["12","T","II","III","6","4"]},
    "G6": {"fingering":["12","T","II","IV","V","4"]},
    "F#3": {"fingering":["T","I","II","III","IV","V","VI","2","3"], "alternates": [["T","I","II","III","IV","V","VI","2"], ["T","I","II","III","IV","V","VI","B"]]},
    "G#3": {"fingering":["T","I","II","III","IV","V","VI","4"]},
    "A#3": {"fingering":["T","I","II","III","IV"]},
    "Db4": {"fingering":["T","I","II","III","6"]},
    "D#4": {"fingering":["T","I","II","7"], "alternates": [["T","I","II","7L"]]},
    "F#4": {"fingering":["I"], "alternates": [["T","7","8"]]},
    "G#4": {"fingering":["9"], "alternates": [["9","IV","V","VI"]]},
    "A#4": {"fingering":["10","12"], "alternates": [["10","12","IV","V","VI"], ["10","11"]]},
    "Db5": {"fingering":["12","T","I","II","III","IV","V","VI","2"], "alternates": [["12","T","I","II","III","IV","V","VI","B"]]},
    "D#5": {"fingering":["12","T","I","II","III","IV","V","VI","4"]},
    "F#5": {"fingering":["12","T","I","II","III","V"], "alternates": [["12","T","I","II","III","IV","5"]]},
    "G#5": {"fingering":["12","T","I","II","III","6"]},
    "A#5": {"fingering":["12","T","I","II","7"], "alternates": [["12","T","I","II","7L"], ["I","IV"]]},
    "Db6": {"fingering":["12","T","II","III","IV","V"]},
    "D#6": {"fingering":["12","T","II","III","IV","5","4"], "alternates": [["12","T","II","III","V","4"]]},
    "F#6": {"fingering":["12","T","II","4"]},
  },
  levels: {
    "Level 1": ["C4","D4","E4","F4","G4"],
    "Level 2": ["A3","B3","C4","D4","E4","F4","G4","A4"],
    "Level 3": ["F3","G3","A3","Bb3","B3","C4","D4","E4","F4","G4","A4","Bb4"],
    "Level 4": ["F3","G3","A3","Bb3","B3","C4","D4","Eb4","E4","F4","F#4","G4","A4","Bb4"],
  },
  scaleRoots: {
    "C": "C4",
    "F": "F4",
    "Bb": "Bb3",
    "Eb": "Eb4",
    "Ab": "Ab3",
    "Db": "Db4",
    "Gb": "Gb3",
    "Cb": "Cb4",
    "G": "G3",
    "D": "D4",
    "A": "A3",
    "E": "E4",
    "B": "B3",
    "F#": "F#4",
    "C#": "C#4",
  },
  minorRoots: {
    "A": "A3",
    "D": "D4",
    "G": "G3",
    "C": "C4",
    "F": "F4",
    "Bb": "Bb3",
    "Eb": "Eb4",
    "Ab": "Ab3",
    "E": "E4",
    "B": "B3",
    "F#": "F#4",
    "C#": "C#4",
    "G#": "G#3",
    "D#": "D#4",
    "A#": "A#3",
  },
  chromaticRoot: "C4",
});
