// Instrument-specific data. Shared scale rules live in js/scales.js.
InstrumentBuilder.build({
  id: "Double_Horn",
  clef: "treble",
  transpose: {"semitones":7,"steps":4},
  notes: {
    "G3": {"fingering":[]},
    "A3": {"fingering":["1","2"]},
    "B3": {"fingering":["2"]},
    "C4": {"fingering":[]},
    "D4": {"fingering":["1"]},
    "E4": {"fingering":[]},
    "F4": {"fingering":["1"]},
    "G4": {"fingering":[]},
    "A4": {"fingering":["T","1","2"]},
    "B4": {"fingering":["T","2"]},
    "C5": {"fingering":["T"]},
    "D5": {"fingering":["T","1","2"]},
    "E5": {"fingering":["T","2"]},
    "F5": {"fingering":["T"]},
    "G5": {"fingering":["T"]},
    "A5": {"fingering":["T","1","2"]},
    "B5": {"fingering":["T","2"]},
    "C6": {"fingering":["T"]},
    "F#3": {"fingering":["2"]},
    "G#3": {"fingering":["2","3"]},
    "A#3": {"fingering":["1"]},
    "Db4": {"fingering":["1","2"]},
    "D#4": {"fingering":["2"]},
    "F#4": {"fingering":["2"]},
    "G#4": {"fingering":["T","2","3"]},
    "A#4": {"fingering":["T","1"]},
    "Db5": {"fingering":["T","2","3"]},
    "D#5": {"fingering":["T","1"]},
    "F#5": {"fingering":["T","2"]},
    "G#5": {"fingering":["T","2","3"]},
    "A#5": {"fingering":["T","1"]},
  },
  levels: {
    "Level 1": ["C4","D4","E4","F4","G4"],
    "Level 2": ["F3","G3","A3","Bb3","B3","C4","D4","E4","F4","G4","A4","Bb4","C5","D5"],
    "Level 3": ["F3","G3","A3","Bb3","B3","C4","D4","Eb4","E4","F4","G4","A4","Bb4","C5","D5","Eb5"],
    "Level 4": ["F3","G3","A3","Bb3","B3","C4","D4","Eb4","E4","F4","G4","Ab4","A4","Bb4","B4","C5","D5","Eb5"],
  },
  scaleRoots: {
    "C": "C4",
    "F": "F3",
    "Bb": "Bb3",
    "Eb": "Eb4",
    "Ab": "Ab3",
    "Db": "Db4",
    "Gb": "Gb3",
    "Cb": "Cb4",
    "G": "G3",
    "D": "D4",
    "A": "A3",
    "E": "E4",
    "B": "B3",
    "F#": "F#3",
    "C#": "C#4",
  },
  minorRoots: {
    "A": "A3",
    "D": "D4",
    "G": "G3",
    "C": "C4",
    "F": "F3",
    "Bb": "Bb3",
    "Eb": "Eb4",
    "Ab": "Ab3",
    "E": "E4",
    "B": "B3",
    "F#": "F#3",
    "C#": "C#4",
    "G#": "G#3",
    "D#": "D#4",
    "A#": "A#3",
  },
  chromaticRoot: "F3",
});
