// Instrument-specific data. Shared scale rules live in js/scales.js.
InstrumentBuilder.build({
  id: "Trumpet",
  clef: "treble",
  transpose: {"semitones":2,"steps":1},
  notes: {
    "G3": {"fingering":["1","3"]},
    "A3": {"fingering":["1","2"]},
    "B3": {"fingering":["2"]},
    "C4": {"fingering":[]},
    "D4": {"fingering":["1","3"]},
    "E4": {"fingering":["1","2"]},
    "F4": {"fingering":["1"]},
    "G4": {"fingering":[], "alternates": ["1", "3"]},
    "A4": {"fingering":["1","2"]},
    "B4": {"fingering":["2"]},
    "C5": {"fingering":[]},
    "D5": {"fingering":["1"]},
    "E5": {"fingering":[]},
    "F5": {"fingering":["1"]},
    "G5": {"fingering":[]},
    "A5": {"fingering":["1","2"]},
    "B5": {"fingering":["2"]},
    "C6": {"fingering":[]},
    "F#3": {"fingering":["1","2","3"]},
    "G#3": {"fingering":["2","3"]},
    "A#3": {"fingering":["1"]},
    "Db4": {"fingering":["1","2","3"]},
    "D#4": {"fingering":["2","3"]},
    "F#4": {"fingering":["2"]},
    "G#4": {"fingering":["2","3"]},
    "A#4": {"fingering":["1"]},
    "Db5": {"fingering":["1","2"]},
    "D#5": {"fingering":["2"]},
    "F#5": {"fingering":["2"]},
    "G#5": {"fingering":["2","3"]},
    "A#5": {"fingering":["1"]},
  },
  levels: {
    "Level 1": ["C4","D4","E4","F4","G4"],
    "Level 2": ["A3","B3","C4","D4","E4","F4","G4","A4"],
    "Level 3": ["A3","Bb3","B3","C4","D4","E4","F4","G4","A4","Bb4","C5"],
    "Level 4": ["A3","Bb3","B3","C4","D4","Eb4","E4","F4","F#4","G4","A4","Bb4","B4","C5"],
  },
  scaleRoots: {
    "C": "C4",
    "F": "F4",
    "Bb": "Bb3",
    "Eb": "Eb4",
    "Gb": "Gb4",
    "Cb": "Cb4",
    "G": "G4",
    "D": "D4",
    "A": "A3",
    "E": "E4",
    "B": "B3",
    "F#": "F#4",
    "C#": "C#4",
  },
  minorRoots: {
    "A": "A3",
    "D": "D4",
    "G": "G4",
    "C": "C4",
    "F": "F4",
    "Bb": "Bb3",
    "Eb": "Eb4",
    "Ab": "Ab3",
    "E": "E4",
    "B": "B3",
    "F#": "F#4",
    "C#": "C#4",
    "G#": "G#4",
    "D#": "D#4",
    "A#": "A#3",
  },
  chromaticRoot: "C4",
});
